apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: git-clone-template
spec:
  entrypoint: main
  # serviceAccountName: argo-user
  volumes:
    - name: workspace
      emptyDir: {}

  templates:
    - name: main
      inputs:
        parameters:
          - name: bb_user
            description: "Repository URL (e.g., github.com/username/repo.git)"
          - name: bb_token
            description: "Bearer token for authentication"
          - name: git_repo
            description: "Repository URL (e.g., github.com/username/repo.git)"
          - name: branch
            description: "Branch to clone"
          
      steps:
        - - name: git-clone
            template: git-clone
            arguments:
              parameters:
                - name: bb_user
                  value: "{{inputs.parameters.bb_user}}"
                - name: bb_token
                  value: "{{inputs.parameters.bb_token}}"
                - name: git_repo
                  value: "{{inputs.parameters.git_repo}}"
                - name: branch
                  value: "{{inputs.parameters.branch}}"               
    - name: git-clone
      inputs:
        parameters:
          - name: bb_user
          - name: bb_token
          - name: git_repo
          - name: branch
      container:
        image: alpine/git
        command: [sh, -c]
        args: 
          - |
            set -e
            bb_user={{inputs.parameters.bb_user}}
            bb_token={{inputs.parameters.bb_token}}
            repo={{inputs.parameters.git_repo}}
            git_url="https://x-token-auth:${bb_token}@bitbucket.org/admarketplace/${repo}.git"
            git clone -b {{inputs.parameters.branch}} $git_url
            cd $repo
            ls
            git status
        # volumeMounts:
        #   - name: workspace
        #     mountPath: /workspace