apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo
resources:
- namespace.yaml
- crds
- workflow-controller
- argo-server

patches:
 - target:
      kind: Service
      name: argo-server 
   path: service-patch.yaml
