apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: latest
resources:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis
- ./notification
- ./applicationset-controller
- ./redis-secret.yaml

patches:
 - target:
      kind: Service
      name: argocd-server 
   path: service-patch.yaml
