apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: guestbook
  namespace: kargo-simple
spec:
  interval: 1m
  subscriptions:
  - image:
      repoURL: iarjune/argo
      imageSelectionStrategy: SemVer
