apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: guestbook-test
  namespace: kargo-simple
spec:
  entrypoint: test-guestbook
  arguments:
    parameters:
    - name: stage
      value: "dev"
    - name: namespace
      value: "guestbook-simple-dev"
  templates:
  - name: test-guestbook
    steps:
    - - name: health-check
        template: http-test
        arguments:
          parameters:
          - name: url
            value: "http://guestbook.{{workflow.parameters.namespace}}.svc.cluster.local"
    - - name: smoke-test
        template: smoke-test
        arguments:
          parameters:
          - name: namespace
            value: "{{workflow.parameters.namespace}}"

  # HTTP health check template
  - name: http-test
    inputs:
      parameters:
      - name: url
    container:
      image: curlimages/curl:latest
      command: [sh, -c]
      args:
      - |
        echo "Testing endpoint: {{inputs.parameters.url}}"
        for i in 1 2 3 4 5; do
          echo "Attempt $i/5..."
          if curl -f -s {{inputs.parameters.url}} > /dev/null; then
            echo "✓ Health check passed"
            exit 0
          fi
          echo "✗ Health check failed, retrying..."
          sleep 5
        done
        echo "✗ Health check failed after 5 attempts"
        exit 1

  # Smoke test template (customize with your actual tests)
  - name: smoke-test
    inputs:
      parameters:
      - name: namespace
    container:
      image: curlimages/curl:latest
      command: [sh, -c]
      args:
      - |
        echo "Running smoke tests in namespace: {{inputs.parameters.namespace}}"
        
        # Example: Test that service responds
        SERVICE_URL="http://guestbook.{{inputs.parameters.namespace}}.svc.cluster.local"
        
        echo "Testing service availability..."
        RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $SERVICE_URL)
        
        if [ "$RESPONSE" = "200" ]; then
          echo "✓ Service returned HTTP 200"
        else
          echo "✗ Service returned HTTP $RESPONSE (expected 200)"
          exit 1
        fi
        
        echo "✓ All smoke tests passed"
        exit 0
