apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: atlas-operator 
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: ghcr.io/ariga/charts
    targetRevision: 0.7.2
    chart: atlas-operator 
  destination:
    server: https://192.168.0.110:6443
    namespace: atlas-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
