apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-cluster1
  namespace: argocd 
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/iarjune/argolab.git
    targetRevision: HEAD
    path: components/mysql-operator
  destination:
    server: https://192.168.0.110:6443
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
