apiVersion: v1
kind: Service
metadata:
  name: nginxdemos-hello
spec:
  selector:
    app: nginxdemos-hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: hello
  type: LoadBalancer
