apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginxdemos-hello
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginxdemos-hello
  template:
    metadata:
      labels:
        app: nginxdemos-hello
    spec:
      containers:
      - image: nginxdemos/hello
        name: nginxdemos-hello
        ports:
        - containerPort: 80
          name: hello
