apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-user-role-binding-wf
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: executor
subjects:
  - kind: ServiceAccount
    name: default
